/// <reference types= "cypress" /> 
describe('template spec', () => {
  it('log in ', () => {
    cy.visit('https://automationteststore.com/index.php?rt=account/login')
    cy.get('#loginFrm_loginname').type('nooryousef12')
    cy.get('#loginFrm_password').type('ab1993Cd')
    cy.get('#loginFrm > fieldset > .btn').click()
    cy.get(':nth-child(1) > .active').click()
    cy.get('#block_frame_latest_1770 > .thumbnails > :nth-child(1) > .thumbnail > .pricetag > .productcart > .fa').click()
    cy.get('#block_frame_bestsellers_1771 > .thumbnails > :nth-child(4) > .thumbnail > .pricetag > .productcart > .fa').click()
    cy.get('#block_frame_latest_1770 > .thumbnails > :nth-child(3) > .thumbnail > .pricetag > .productcart > .fa').click()
    cy.get('.block_7 > .nav > .dropdown > .dropdown-toggle').click()
    cy.get('#cart_quantity68').clear()
    cy.get('#cart_quantity68').type('1')
    cy.get('#cart_quantity65').clear()
    cy.get('#cart_quantity65').type('1')
    cy.get('#cart_quantity66').clear()
    cy.get('#cart_quantity66').type('1')
    cy.get('#cart_checkout1').click()
    cy.get('#checkout_btn').click()
  })
})